# Generated by Django 5.1.4 on 2025-01-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationproduit',
            name='quantite',
            field=models.FloatField(),
        ),
    ]
