# Generated by Django 5.1.4 on 2025-01-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_messagereservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereservation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
