# Generated by Django 5.1.4 on 2025-01-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='etat',
            field=models.CharField(choices=[('pret', 'Prêt'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_attente', 'En attente')], default='en_cours', max_length=20),
        ),
    ]
