# Generated by Django 5.1.4 on 2025-01-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produit_type_alter_produit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
