# Generated by Django 5.1.4 on 2025-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_produit_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fonctions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
