# Generated by Django 5.1.4 on 2025-01-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_alter_produit_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='fonctions',
        ),
        migrations.AlterField(
            model_name='produit',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.famille'),
        ),
    ]
