# Generated by Django 5.1.4 on 2025-01-14 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_remove_produit_fonctions_alter_produit_famille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='famille',
        ),
        migrations.AddField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produit',
            name='familles',
            field=models.ManyToManyField(blank=True, to='produits.famille'),
        ),
    ]
