# Generated by Django 5.1.5 on 2025-02-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_remove_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil',
            field=models.FloatField(default=0.0),
        ),
    ]
