# Generated by Django 5.1.4 on 2025-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='annee',
            field=models.CharField(blank=True, choices=[('1A', '1ère Année'), ('2A', '2ème Année'), ('3A', '3ème Année')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Etudiant'), ('preparateur', 'Preparateur'), ('administrateur', 'Administrateur')], default='etudiant', max_length=100),
        ),
    ]
