# Generated by Django 5.1.4 on 2025-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_annee_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='groupe',
            field=models.CharField(blank=True, choices=[('1', 'groupe 1'), ('2', 'groupe 2'), ('3', 'groupe 3'), ('4', 'groupe 4')], max_length=1, null=True),
        ),
    ]
