# Generated by Django 5.1.4 on 2025-01-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='annee',
            field=models.CharField(blank=True, choices=[('1ère année', '1ère année'), ('2ème année', '2ème année'), ('3ème année', '3ème année')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groupe',
            field=models.CharField(blank=True, choices=[('Groupe 1', 'Groupe 1'), ('Groupe 2', 'Groupe 2'), ('Groupe 3', 'Groupe 3'), ('Groupe 4', 'Groupe 4')], max_length=100, null=True),
        ),
    ]
