# Generated by Django 4.2.16 on 2024-10-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_models', '0002_alter_utilisateur_options_utilisateur_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='produits',
        ),
    ]
