# Generated by Django 4.2.16 on 2024-10-09 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_models', '0003_remove_reservation_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='stockage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_models.stockage'),
        ),
    ]
