# Generated by Django 4.2.16 on 2024-10-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_models', '0004_alter_produit_stockage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationproduit',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='reservation_models.reservation'),
        ),
    ]
